# Generated by Django 5.0.4 on 2024-05-20 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 20, 7, 46, 31, 95248, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
